[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Content-Type = "font/woff"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Content-Type = "font/woff2"

[[headers]]
  for = "/*.ttf"
  [headers.values]
    Content-Type = "font/ttf"

[[headers]]
  for = "/*.eot"
  [headers.values]
    Content-Type = "application/vnd.ms-fontobject"

[[headers]]
  for = "/*.otf"
  [headers.values]
    Content-Type = "font/otf" 